In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df = pickle.load(open('dataset_level2.pkl','rb'))

In [3]:
df
# batting_team
# bowling team
# city
# current score
# ball left
# wickets left
# current rr
# last five

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,Wankhede Stadium
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,Wankhede Stadium
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,Wankhede Stadium
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,Wankhede Stadium
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,Wankhede Stadium
...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi,Feroz Shah Kotla
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi,Feroz Shah Kotla
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi,Feroz Shah Kotla
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi,Feroz Shah Kotla
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi,Feroz Shah Kotla

In [4]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [5]:
df.drop(columns=['venue'], inplace=True)

In [6]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai
...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi

In [7]:
df['city'].value_counts()

city
Mumbai            16044
Kolkata            8879
Chennai            8706
Delhi              6970
Jaipur             6480
Hyderabad          5968
Ahmedabad          4730
Unknown            4225
Abu Dhabi          3574
Chandigarh         3100
Bengaluru          2737
Lucknow            2624
Bangalore          2396
Pune               2122
Visakhapatnam      1375
Dubai              1374
Sharjah            1245
Navi Mumbai        1133
Mohali             1090
Dharamsala          938
Centurion           753
Durban              746
Guwahati            623
Ranchi              593
Cape Town           497
Cuttack             493
Port Elizabeth      370
Indore              252
Kimberley           243
New Chandigarh      211
East London         126
Bloemfontein        124
Name: count, dtype: int64

In [8]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts()>600].index.tolist()

In [9]:
df=df[df['city'].isin(eligible_cities)]

In [10]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai
...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi

In [11]:
# Convert runs to numbers 
df['runs'] = pd.to_numeric(df['runs'], errors='coerce').fillna(0).astype(int)

C:\Users\Patel Meet\AppData\Local\Temp\ipykernel_13292\2191771701.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runs'] = pd.to_numeric(df['runs'], errors='coerce').fillna(0).astype(int)

In [12]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

C:\Users\Patel Meet\AppData\Local\Temp\ipykernel_13292\2248842435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [13]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4
...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi,154
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi,160
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi,161
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi,161
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi,162

In [14]:
df = df.copy()
df['overs']=df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no']=df['ball'].apply(lambda x:str(x).split(".")[1])
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5
...,...,...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi,154,19,2
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi,160,19,3
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi,161,19,4
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi,161,19,5
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi,162,19,6

In [15]:
df['overs'] = df['overs'].astype(int)
df['ball_no'] = df['ball_no'].astype(int)

In [16]:
df['balls_bowled'] = (df['overs'] * 6) + df['ball_no']
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1,1
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2,2
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3,3
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4,4
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi,154,19,2,116
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi,160,19,3,117
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi,161,19,4,118
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi,161,19,5,119
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi,162,19,6,120

In [17]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x: 0 if x < 0 else x)
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1,1,119
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2,2,118
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3,3,117
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4,4,116
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,0,Delhi,154,19,2,116,4
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,0,Delhi,160,19,3,117,3
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,0,Delhi,161,19,4,118,2
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,B Kumar,Delhi,161,19,5,119,1
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,0,Delhi,162,19,6,120,0

In [18]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
df['player_dismissed'] = df['player_dismissed'].astype('int')
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()
df['wickets_left'] = 10 - df['player_dismissed']

In [19]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1,1,119,10
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2,2,118,10
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3,3,117,10
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4,4,116,10
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,7,Delhi,154,19,2,116,4,3
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,7,Delhi,160,19,3,117,3,3
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,7,Delhi,161,19,4,118,2,3
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,8,Delhi,161,19,5,119,1,2
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,8,Delhi,162,19,6,120,0,2

In [20]:
df['current_run_rate'] = (df['current_score']*6)/df['balls_bowled']
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left,current_run_rate
741,8,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1,1,119,10,6.000000
742,8,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2,2,118,10,6.000000
743,8,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3,3,117,10,6.000000
744,8,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4,4,116,10,4.500000
745,8,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5,5,115,10,4.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142289,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,7,Delhi,154,19,2,116,4,3,7.965517
142290,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,7,Delhi,160,19,3,117,3,3,8.205128
142291,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,7,Delhi,161,19,4,118,2,3,8.186441
142292,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,8,Delhi,161,19,5,119,1,2,8.117647
142293,1168,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,8,Delhi,162,19,6,120,0,2,8.100000

In [21]:
#df['last_5_over'] = df.groupby('match_id')['runs'].transform(lambda x: x.rolling(window=30, min_periods=1).sum())

In [22]:
#df

In [23]:
final_df=df.groupby('match_id').sum()['runs'].reset_index().merge(df, on='match_id')
final_df

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left,current_run_rate
0,8,178,Kolkata Knight Riders,Mumbai Indians,0.1,1,0,Mumbai,1,0,1,1,119,10,6.000000
1,8,178,Kolkata Knight Riders,Mumbai Indians,0.2,1,0,Mumbai,2,0,2,2,118,10,6.000000
2,8,178,Kolkata Knight Riders,Mumbai Indians,0.3,1,0,Mumbai,3,0,3,3,117,10,6.000000
3,8,178,Kolkata Knight Riders,Mumbai Indians,0.4,0,0,Mumbai,3,0,4,4,116,10,4.500000
4,8,178,Kolkata Knight Riders,Mumbai Indians,0.5,1,0,Mumbai,4,0,5,5,115,10,4.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87827,1168,162,Sunrisers Hyderabad,Kolkata Knight Riders,19.2,0,7,Delhi,154,19,2,116,4,3,7.965517
87828,1168,162,Sunrisers Hyderabad,Kolkata Knight Riders,19.3,6,7,Delhi,160,19,3,117,3,3,8.205128
87829,1168,162,Sunrisers Hyderabad,Kolkata Knight Riders,19.4,1,7,Delhi,161,19,4,118,2,3,8.186441
87830,1168,162,Sunrisers Hyderabad,Kolkata Knight Riders,19.5,0,8,Delhi,161,19,5,119,1,2,8.117647
87831,1168,162,Sunrisers Hyderabad,Kolkata Knight Riders,19.6,1,8,Delhi,162,19,6,120,0,2,8.100000

In [24]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','current_run_rate','runs_x']]
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate,runs_x
0,Kolkata Knight Riders,Mumbai Indians,Mumbai,1,119,10,6.000000,178
1,Kolkata Knight Riders,Mumbai Indians,Mumbai,2,118,10,6.000000,178
2,Kolkata Knight Riders,Mumbai Indians,Mumbai,3,117,10,6.000000,178
3,Kolkata Knight Riders,Mumbai Indians,Mumbai,3,116,10,4.500000,178
4,Kolkata Knight Riders,Mumbai Indians,Mumbai,4,115,10,4.800000,178
...,...,...,...,...,...,...,...,...
87827,Sunrisers Hyderabad,Kolkata Knight Riders,Delhi,154,4,3,7.965517,162
87828,Sunrisers Hyderabad,Kolkata Knight Riders,Delhi,160,3,3,8.205128,162
87829,Sunrisers Hyderabad,Kolkata Knight Riders,Delhi,161,2,3,8.186441,162
87830,Sunrisers Hyderabad,Kolkata Knight Riders,Delhi,161,1,2,8.117647,162
87831,Sunrisers Hyderabad,Kolkata Knight Riders,Delhi,162,0,2,8.100000,162

In [25]:
final_df.isnull().sum()

batting_team        0
bowling_team        0
city                0
current_score       0
balls_left          0
wickets_left        0
current_run_rate    0
runs_x              0
dtype: int64

In [26]:
final_df=final_df.sample(final_df.shape[0])
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate,runs_x
86178,Sunrisers Hyderabad,Kolkata Knight Riders,Hyderabad,69,44,6,5.447368,142
20282,Royal Challengers Bengaluru,Delhi Capitals,Ahmedabad,47,78,8,6.714286,171
19441,Mumbai Indians,Delhi Capitals,Chennai,82,54,5,7.454545,137
40688,Sunrisers Hyderabad,Mumbai Indians,Mumbai,185,8,7,9.910714,200
69976,Royal Challengers Bengaluru,Chennai Super Kings,Chennai,37,96,10,9.250000,205
...,...,...,...,...,...,...,...,...
7018,Punjab Kings,Rajasthan Royals,Jaipur,146,23,7,9.030928,184
66054,Punjab Kings,Rajasthan Royals,Jaipur,41,93,9,9.111111,153
66980,Chennai Super Kings,Kolkata Knight Riders,Chennai,98,36,8,7.000000,153
5703,Sunrisers Hyderabad,Kolkata Knight Riders,Hyderabad,32,101,10,10.105263,172
2137,Royal Challengers Bengaluru,Kolkata Knight Riders,Kolkata,39,95,9,9.360000,176

In [27]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [28]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate
49403,Punjab Kings,Sunrisers Hyderabad,Hyderabad,98,64,9,10.500000
37445,Rajasthan Royals,Mumbai Indians,Mumbai,171,14,4,9.679245
49426,Punjab Kings,Sunrisers Hyderabad,Hyderabad,140,42,9,10.769231
46800,Chennai Super Kings,Sunrisers Hyderabad,Chennai,110,51,9,9.565217
79274,Delhi Capitals,Chennai Super Kings,Delhi,8,111,10,5.333333
...,...,...,...,...,...,...,...
69194,Royal Challengers Bengaluru,Chennai Super Kings,Mumbai,148,12,6,8.222222
39825,Gujarat Titans,Sunrisers Hyderabad,Ahmedabad,12,106,9,5.142857
12584,Kolkata Knight Riders,Delhi Capitals,Abu Dhabi,64,63,7,6.736842
4010,Royal Challengers Bengaluru,Kolkata Knight Riders,Bengaluru,71,65,9,7.745455
29216,Rajasthan Royals,Mumbai Indians,Navi Mumbai,3,111,10,2.000000

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

c:\Users\Patel Meet\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\compat.py:105: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [30]:
X = final_df[['batting_team', 'bowling_team', 'city', 'current_score', 'balls_left', 'wickets_left', 'current_run_rate']]
y = final_df['runs_x']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])], remainder='passthrough')

In [33]:
pipe = Pipeline(steps=[
    ('step1', trf),('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

In [34]:

pipe.fit(X_train, y_train)
print("Model Successfully Train ho gaya! 🎉")

Model Successfully Train ho gaya! 🎉

In [35]:
y_pred = pipe.predict(X_test)

In [36]:
print("R-squared Score (Accuracy):", r2_score(y_test, y_pred))
print("Mean Absolute Error (Runs):", mean_absolute_error(y_test, y_pred))

R-squared Score (Accuracy): 0.905581533908844
Mean Absolute Error (Runs): 4.674860000610352

In [37]:
import pickle
pickle.dump(pipe, open('ipl_pipe.pkl', 'wb'))