In [36]:
import pandas as pd
import numpy as np
import pickle

In [37]:
df = pickle.load(open('dataset_level2.pkl','rb'))

In [38]:
df
# batting_team
# bowling team
# city
# current score
# ball left
# wickets left
# current rr
# last five

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [39]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [40]:
df.drop(columns=['venue'], inplace=True)

In [41]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Unknown
1,2,Australia,Sri Lanka,0.2,0,0,Unknown
2,2,Australia,Sri Lanka,0.3,1,0,Unknown
3,2,Australia,Sri Lanka,0.4,2,0,Unknown
4,2,Australia,Sri Lanka,0.5,0,0,Unknown
...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo

In [42]:
df['city'].value_counts()

city
Unknown               19176
Colombo                8655
Abu Dhabi              5547
Dublin                 5409
Dubai                  5383
                      ...
New Plymouth            122
Derry                   121
Gwalior                 121
Pokhara                 119
FTZ Sports Complex      116
Name: count, Length: 166, dtype: int64

In [43]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts()>600].index.tolist()

In [44]:
df=df[df['city'].isin(eligible_cities)]

In [45]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Unknown
1,2,Australia,Sri Lanka,0.2,0,0,Unknown
2,2,Australia,Sri Lanka,0.3,1,0,Unknown
3,2,Australia,Sri Lanka,0.4,2,0,Unknown
4,2,Australia,Sri Lanka,0.5,0,0,Unknown
...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo

In [46]:
# Convert runs to numbers 
df['runs'] = pd.to_numeric(df['runs'], errors='coerce').fillna(0).astype(int)

C:\Users\Patel Meet\AppData\Local\Temp\ipykernel_24928\2191771701.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runs'] = pd.to_numeric(df['runs'], errors='coerce').fillna(0).astype(int)

In [47]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

C:\Users\Patel Meet\AppData\Local\Temp\ipykernel_24928\2248842435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [48]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3
...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo,125
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo,125
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo,127
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [49]:
df = df.copy()
df['overs']=df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no']=df['ball'].apply(lambda x:str(x).split(".")[1])
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5
...,...,...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7

In [50]:
df['overs'] = df['overs'].astype(int)
df['ball_no'] = df['ball_no'].astype(int)

In [51]:
df['balls_bowled'] = (df['overs'] * 6) + df['ball_no']
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1,1
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2,2
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3,3
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4,4
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121

In [52]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x: 0 if x < 0 else x)
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1,1,119
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2,2,118
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3,3,117
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4,4,116
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3
581768,4787,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2
581769,4787,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1
581770,4787,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0
581771,4787,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0

In [53]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
df['player_dismissed'] = df['player_dismissed'].astype('int')
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()
df['wickets_left'] = 10 - df['player_dismissed']

In [54]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1,1,119,10
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2,2,118,10
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3,3,117,10
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4,4,116,10
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2
581768,4787,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2
581769,4787,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1
581770,4787,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1
581771,4787,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1

In [55]:
df['current_run_rate'] = (df['current_score']*6)/df['balls_bowled']
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left,current_run_rate
0,2,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1,1,119,10,0.000000
1,2,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2,2,118,10,0.000000
2,2,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3,3,117,10,2.000000
3,2,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4,4,116,10,4.500000
4,2,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581767,4787,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256
581768,4787,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932
581769,4787,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521
581770,4787,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000
581771,4787,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107

In [56]:
final_df=df.groupby('match_id').sum()['runs'].reset_index().merge(df, on='match_id')
final_df

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,current_score,overs,ball_no,balls_bowled,balls_left,wickets_left,current_run_rate
0,2,168,Australia,Sri Lanka,0.1,0,0,Unknown,0,0,1,1,119,10,0.000000
1,2,168,Australia,Sri Lanka,0.2,0,0,Unknown,0,0,2,2,118,10,0.000000
2,2,168,Australia,Sri Lanka,0.3,1,0,Unknown,1,0,3,3,117,10,2.000000
3,2,168,Australia,Sri Lanka,0.4,2,0,Unknown,3,0,4,4,116,10,4.500000
4,2,168,Australia,Sri Lanka,0.5,0,0,Unknown,3,0,5,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218469,4787,128,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256
218470,4787,128,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932
218471,4787,128,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521
218472,4787,128,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000
218473,4787,128,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107

In [57]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','current_run_rate','runs_x']]
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate,runs_x
0,Australia,Sri Lanka,Unknown,0,119,10,0.000000,168
1,Australia,Sri Lanka,Unknown,0,118,10,0.000000,168
2,Australia,Sri Lanka,Unknown,1,117,10,2.000000,168
3,Australia,Sri Lanka,Unknown,3,116,10,4.500000,168
4,Australia,Sri Lanka,Unknown,3,115,10,3.600000,168
...,...,...,...,...,...,...,...,...
218469,Sri Lanka,Australia,Colombo,125,3,2,6.410256,128
218470,Sri Lanka,Australia,Colombo,125,2,2,6.355932,128
218471,Sri Lanka,Australia,Colombo,125,1,1,6.302521,128
218472,Sri Lanka,Australia,Colombo,127,0,1,6.350000,128
218473,Sri Lanka,Australia,Colombo,128,0,1,6.347107,128

In [58]:
final_df.isnull().sum()

batting_team        0
bowling_team        0
city                0
current_score       0
balls_left          0
wickets_left        0
current_run_rate    0
runs_x              0
dtype: int64

In [59]:
final_df=final_df.sample(final_df.shape[0])
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate,runs_x
205158,South Africa,Pakistan,Unknown,46,40,5,3.450000,83
119730,Bangladesh,United States of America,Houston,41,83,8,6.648649,153
8047,New Zealand,Pakistan,Unknown,47,79,10,6.878049,150
50757,Sri Lanka,West Indies,Coolidge,129,2,6,6.559322,131
161164,South Africa,Scotland,London,110,43,8,8.571429,211
...,...,...,...,...,...,...,...,...
106026,Australia,New Zealand,Auckland,40,101,9,12.631579,174
31852,Australia,England,Melbourne,94,27,6,6.064516,132
135278,Canada,Netherlands,Utrecht,99,21,4,6.000000,132
23368,Pakistan,Australia,Unknown,51,81,9,7.846154,147
64844,New Zealand,Australia,Dubai,40,72,9,5.000000,172

In [60]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [61]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,current_run_rate
191600,Pakistan,Ireland,Dublin,42,76,8,5.727273
113673,Ireland,Pakistan,Lauderhill,86,28,1,5.608696
190526,South Africa,Sri Lanka,Hambantota,100,42,8,7.692308
208260,India,Australia,Unknown,9,113,10,7.714286
207269,Australia,South Africa,Durban,4,115,10,4.800000
...,...,...,...,...,...,...,...
149660,Sri Lanka,Pakistan,Abu Dhabi,38,93,8,8.444444
97715,Bangladesh,Ireland,Chattogram,94,30,3,6.266667
14789,Pakistan,Australia,Unknown,97,52,8,8.558824
145051,Bangladesh,Pakistan,Lahore,8,107,10,3.692308
194265,Sri Lanka,South Africa,Potchefstroom,81,55,8,7.476923

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [63]:
X = final_df[['batting_team', 'bowling_team', 'city', 'current_score', 'balls_left', 'wickets_left', 'current_run_rate']]
y = final_df['runs_x']

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:
trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])], remainder='passthrough')

In [66]:
pipe = Pipeline(steps=[
    ('step1', trf),('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

In [67]:

pipe.fit(X_train, y_train)
print("Model Successfully Train ho gaya! 🎉")

Model Successfully Train ho gaya! 🎉

In [68]:
y_pred = pipe.predict(X_test)

In [69]:
print("R-squared Score (Accuracy):", r2_score(y_test, y_pred))
print("Mean Absolute Error (Runs):", mean_absolute_error(y_test, y_pred))

R-squared Score (Accuracy): 0.9524706602096558
Mean Absolute Error (Runs): 3.443678379058838

In [71]:
import pickle
pickle.dump(pipe, open('t20_pipe.pkl', 'wb'))